### ISSUE TITLE
Lab Report 5 Feedback

### ISSUE THREAD

**Issue by farnaf** [junlinchen12138/cse15l-lab-reports1#5]
Here is your feedback for Lab Report 5:

- [ ] Explains how tests with different results were found (`diff`, manual search, etc)

Test 1:
- [ ] Describes which, if any, implementation is correct by showing both actual outputs and indicating what the expected output is
- [ ] Describes bug in code for one of the incorrect implementation and shows the code that should be fixed.

Test 2:
- [ ] Describes which, if any, implementation is correct by showing both actual outputs and indicating what the expected output is
- [ ] Describes bug in code for one of the incorrect implementation and shows the code that should be fixed.

Additional comments from your grader:

Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by junlinchen12138** [comment]
Hi, I just updates my lab report 5

**Comment by farnaf** [comment]
Could you make a regrade request on gradescope?

**Comment by junlinchen12138** [comment]
there is no regrade request bottom on this report

**Comment by farnaf** [comment]
It closed at 11:59pm.

But no problem, can you provide a link to your gradescope submission here? I'll review + update your grade

**Comment by junlinchen12138** [comment]
this is the link to my lab report:
https://junlinchen12138.github.io/cse15l-lab-reports1/lab-report-5-week-10.html

**Comment by junlinchen12138** [comment]
I think the webpage is not updated correctly, and this is my repository
page :cse15l-lab-reports1/lab-report-5-week-10.md at main ·
junlinchen12138/cse15l-lab-reports1 (github.com)
<https://github.com/junlinchen12138/cse15l-lab-reports1/blob/main/lab-report-5-week-10.md>

**Comment by junlinchen12138** [comment]
Hello, Is the link working? Also, for my report 4, I submitted the regrade request weeks ago and my grade is not been updated yet.

**Comment by junlinchen12138** [comment]
https://canvas.ucsd.edu/courses/33600/external_tools/80
This is the link to my gradescope

**Comment by farnaf** [comment]
Yes, I updated your grade! 

We're still handling regrades for lab report 4, don't worry(:

**Comment by junlinchen12138** [comment]
Hi, I just updates my week 10 lab report 5 and there is no regrade request
on Gradescope

**Comment by junlinchen12138** [comment]
Hello, Is the link working? Also, for my report 4, I submitted the regrade
request weeks ago and my grade is not been updated yet.

**Comment by junlinchen12138** [comment]
cse15l-lab-reports1/lab-report-5-week-10.md at main ·
junlinchen12138/cse15l-lab-reports1 (github.com)
<https://github.com/junlinchen12138/cse15l-lab-reports1/blob/main/lab-report-5-week-10.md>
